### ISSUE TITLE
add a tagstack, to be able to pop out from search jump

### ISSUE THREAD

**Issue by jreybert** [mhinz/vim-lookup#2]
Seems to be the beginning of an answer hère.
http://stackoverflow.com/questions/26291758/how-to-manually-push-stack-entry-into-vim-tagstack

**Comment by mhinz** [comment]
Okay, so I had a quick look at `lh-tags`: https://github.com/LucHermitte/lh-tags/blob/7bd0aa45caadd653ba79e421d5272c2512802649/autoload/lh/tags.vim#L819-L823

Basically it cheats by creating a temporary tags file, but since the whole point of the plugin is not to rely on tags.. what about a simple custom stack data structure that holds the positions?

`lookup#lookup()` would add the position (absolute path, line, column) from _before_ jumping and a new function `lookup#pop()` would pop from it.

Then people who want to use that behaviour could simply map the second function theirselves, e.g. to `<c-t>`.

What do you think?

**Comment by jreybert** [comment]
Indeed, the temporary file seems overkill for a simple feature as a tagstack. I think it looks good 👍 

I only wonder what should be the scope of the tagstack: whole vim session, by window, by buffer? It seems that vim vanilla tagstack scope is by window. Furthermore, tagstack is inherited when a window is split. `window-variable` are not inherited, but inheritance is not crucial.

IMO, a tagstack by window (based on window-variable) seems to be enough.

**Comment by mhinz** [comment]
Okay, `lookup#pop()` is on master now. Still undocumented. Please play around with it. :]

**Comment by jreybert** [comment]
\o/ It works like a charm, you can close the issue.
